# Author: Greedysky <greedysky@163.com>

name: linux

on: workflow_call

env:
  TTK_MODULE: QtSpek
  TTK_VERSION: 0.8.5

jobs:
  build:
    name: Build on Qt${{matrix.qt_major}}(${{matrix.os}})
    strategy:
      matrix:
        qt: [qt5, qt6]
        ffmpeg: [ffmpeg3]
        os: [ubuntu-22.04]
        include:
          - ffmpeg: ffmpeg3
            ffmpeg_version: 3.4.14

          - qt: qt5
            qt_major: 5
            qt_version: 5.9.9
            qt_modules:

          - qt: qt6
            qt_major: 6
            qt_version: 6.5.3
            qt_modules: qt5compat

    env:
      QT_VERSION: ${{matrix.qt_version}}
      INSTALL_PATH: /home/runner/work/QtSpek/QtSpek/contrib

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5

      - name: Cache Qt
        uses: actions/cache@v4
        with:
          path: ${{runner.workspace}}/Qt
          key: ${{runner.os}}-QtCache-${{env.QT_VERSION}}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{env.QT_VERSION}}
          target: desktop
          modules: ${{matrix.qt_modules}}
          cache: 'true'

      - name: Install linuxdeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage

      - name: Install dependencies
        run: sudo apt install libfuse2 p7zip-full

      - name: Build library for libspeex
        run: |
          wget https://ftp.osuosl.org/pub/xiph/releases/speex/speex-1.2.1.tar.gz -O speex.tar.gz
          tar -xvf speex.tar.gz
          cd speex-1.2.1
          ./configure --prefix=${{env.INSTALL_PATH}} CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libffmpeg
        run: |
          wget https://ffmpeg.org/releases/ffmpeg-${{matrix.ffmpeg_version}}.tar.gz -O ffmpeg.tar.gz
          tar -xvf ffmpeg.tar.gz
          cd ffmpeg-${{matrix.ffmpeg_version}}
          # fix operand type mismatch for `shr'
          wget https://raw.githubusercontent.com/FFmpeg/FFmpeg/refs/heads/master/libavcodec/x86/mathops.h -O libavcodec/x86/mathops.h
          export PKG_CONFIG_PATH=${{env.INSTALL_PATH}}/lib/pkgconfig:$PKG_CONFIG_PATH
          ./configure --prefix=${{env.INSTALL_PATH}} --enable-shared --disable-static --disable-debug --disable-doc --disable-avdevice --disable-x86asm --disable-network --disable-encoders --disable-indevs --disable-outdevs --disable-iconv --disable-bsfs --disable-programs --disable-d3d11va --disable-dxva2 --disable-muxers --disable-parsers --disable-filters --disable-decoders --enable-decoder=wmav1 --enable-decoder=wmav2 --enable-decoder=ape --enable-decoder=tta --enable-decoder=aac --enable-decoder=alac --enable-decoder=ra_144 --enable-decoder=ra_288 --enable-decoder=shorten --enable-decoder=eac3 --enable-decoder=dca --enable-decoder=truehd --enable-decoder=twinvq --enable-decoder=tak --enable-decoder=adpcm_adx --enable-decoder=pcm_alaw --enable-decoder=pcm_s16be --enable-decoder=pcm_s16le --enable-decoder=gsm --enable-decoder=amrnb --enable-decoder=amrwb --enable-decoder=opus --enable-decoder=ac3 --enable-decoder=mp2 --enable-decoder=mp3 --enable-decoder=dsd_lsbf --enable-decoder=dsd_msbf --enable-decoder=vorbis --enable-decoder=flac --enable-decoder=libspeex --enable-libspeex --extra-cflags="-fPIC -O3 -Wno-incompatible-pointer-types" --extra-cxxflags="-fPIC -O3 -Wno-incompatible-pointer-types"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build project
        run: |
          qmake -v
          qmake "CONFIG+=release" .
          make -j2
        working-directory: ${{github.workspace}}

      - name: Build package
        run: |
          mv bin ${{env.TTK_MODULE}}
          cd ${{env.TTK_MODULE}}
          export LD_LIBRARY_PATH=${{github.workspace}}/contrib/lib:$LD_LIBRARY_PATH
          # add dependency libraries and so on
          linuxdeploy-x86_64.AppImage --executable=${{env.TTK_MODULE}} --appdir=image --plugin=qt
          mv image/usr/lib image/usr/plugins image/usr/bin/qt.conf .
          rm -rf image
          cd ..
          # add install resource
          mkdir ${{env.TTK_MODULE}}/share ${{env.TTK_MODULE}}/doc
          cp CREDITS.md LICENSE README.md utils/resource/LICENSE.QT-LICENSE-AGREEMENT ${{env.TTK_MODULE}}/doc
          cp utils/install.sh utils/uninstall.sh ${{env.TTK_MODULE}}
          cp -r utils/deploy ${{env.TTK_MODULE}}
          cp -r utils/deploy/share/metainfo ${{env.TTK_MODULE}}/share
          # add portable binary package
          7z a ${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-linux-${{matrix.qt}}-x64.7z ${{env.TTK_MODULE}}
        working-directory: ${{github.workspace}}

      - name: Build appimage package
        run: |
          # create usr building dir
          mv ${{env.TTK_MODULE}} usr
          mkdir ${{env.TTK_MODULE}}
          mv usr ${{env.TTK_MODULE}}
          cd ${{env.TTK_MODULE}}
          mv usr/doc .
          # create hack module
          echo -n '#!/bin/sh
           dirpath=`dirname $0`
           tmp="${dirpath#?}"
           if [ "${dirpath%${tmp}}" != "/" ]; then
            dirpath=$PWD/${dirpath}
           fi
           sh ${dirpath}/usr/${{env.TTK_MODULE}}.sh' > ${{env.TTK_MODULE}}
          chmod +x ${{env.TTK_MODULE}}
          # add dependency files
          ln -s ${{env.TTK_MODULE}} AppRun
          cp usr/deploy/share/pixmaps/qtspek.png logo.png
          sh usr/deploy/make_desktop_raw.sh ${{env.TTK_MODULE}}.desktop logo ${{env.TTK_MODULE}}
          cd ..
          # add appimage binary package
          linuxdeploy-plugin-appimage-x86_64.AppImage --appdir=${{env.TTK_MODULE}}
          mv ${{env.TTK_MODULE}}*.AppImage ${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-linux-${{matrix.qt}}-x64.AppImage
        working-directory: ${{github.workspace}}

      - name: Archive artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TTK_VERSION}}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: false
          files: |
            ${{github.workspace}}/${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-linux-${{matrix.qt}}-x64.7z
            ${{github.workspace}}/${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-linux-${{matrix.qt}}-x64.AppImage
