# Author: Greedysky <greedysky@163.com>

name: ubuntu

on: workflow_call

env:
  TTK_MODULE: QtSpek
  TTK_VERSION: 0.8.5

jobs:
  build:
    name: Build on Qt${{matrix.qt_major}}(${{matrix.os}})
    strategy:
      matrix:
        qt: [qt5, qt6]
        ffmpeg: [ffmpeg3]
        os: [ubuntu-22.04, ubuntu-24.04]
        include:
          - ffmpeg: ffmpeg3
            ffmpeg_version: 3.4.14

          - qt: qt5
            qt_major: 5
            qt_version: 5.15.2

          - qt: qt6
            qt_major: 6
            qt_version: 6.9.3

    env:
      QT_VERSION: ${{matrix.qt_version}}
      INSTALL_PATH: /home/runner/work/QtSpek/QtSpek/contrib

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{env.QT_VERSION}}
          target: desktop
          cache: 'true'

      - name: Add patch for Qt5.15.2
        if: env.QT_VERSION == '5.15.2'
        shell: bash
        run: |
          # fix missing <limits> include
          # see QTBUG-89977 https://bugreports.qt.io/browse/QTBUG-89977
          # see QTBUG-90395 https://bugreports.qt.io/browse/QTBUG-90395
          # see QTBUG-93452 https://bugreports.qt.io/browse/QTBUG-93452
          # see here https://codereview.qt-project.org/c/qt/qtbase/+/330713
          sed -i "46i#include <limits>" "${{env.QT_ROOT_DIR}}/include/QtCore/qfloat16.h"
        working-directory: ${{runner.workspace}}

      - name: Install linuxdeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage

      - name: Install dependencies
        run: sudo apt install libfuse2 p7zip-full

      - name: Build library for libspeex
        run: |
          wget https://ftp.osuosl.org/pub/xiph/releases/speex/speex-1.2.1.tar.gz -O speex.tar.gz
          tar -xvf speex.tar.gz
          cd speex-1.2.1
          ./configure --prefix=${{env.INSTALL_PATH}} CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libffmpeg
        run: |
          wget https://ffmpeg.org/releases/ffmpeg-${{matrix.ffmpeg_version}}.tar.gz -O ffmpeg.tar.gz
          tar -xvf ffmpeg.tar.gz
          cd ffmpeg-${{matrix.ffmpeg_version}}
          # fix operand type mismatch for `shr'
          wget https://raw.githubusercontent.com/FFmpeg/FFmpeg/refs/heads/master/libavcodec/x86/mathops.h -O libavcodec/x86/mathops.h
          export PKG_CONFIG_PATH=${{env.INSTALL_PATH}}/lib/pkgconfig:$PKG_CONFIG_PATH
          ./configure --prefix=${{env.INSTALL_PATH}} --enable-shared --disable-static --disable-debug --disable-doc --disable-avdevice --disable-x86asm --disable-network --disable-encoders --disable-indevs --disable-outdevs --disable-iconv --disable-bsfs --disable-programs --disable-d3d11va --disable-dxva2 --disable-muxers --disable-parsers --disable-filters --disable-decoders --enable-decoder=wmav1 --enable-decoder=wmav2 --enable-decoder=ape --enable-decoder=tta --enable-decoder=aac --enable-decoder=alac --enable-decoder=ra_144 --enable-decoder=ra_288 --enable-decoder=shorten --enable-decoder=eac3 --enable-decoder=dca --enable-decoder=truehd --enable-decoder=twinvq --enable-decoder=tak --enable-decoder=adpcm_adx --enable-decoder=pcm_alaw --enable-decoder=pcm_s16be --enable-decoder=pcm_s16le --enable-decoder=gsm --enable-decoder=amrnb --enable-decoder=amrwb --enable-decoder=opus --enable-decoder=ac3 --enable-decoder=mp2 --enable-decoder=mp3 --enable-decoder=dsd_lsbf --enable-decoder=dsd_msbf --enable-decoder=vorbis --enable-decoder=flac --enable-decoder=libspeex --enable-libspeex --extra-cflags="-fPIC -O3 -Wno-incompatible-pointer-types" --extra-cxxflags="-fPIC -O3 -Wno-incompatible-pointer-types"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build project
        run: |
          qmake -v
          qmake "CONFIG+=release" .
          make -j2
        working-directory: ${{github.workspace}}

      - name: Build package
        run: |
          mv bin ${{env.TTK_MODULE}}
          # add install resource
          mkdir ${{env.TTK_MODULE}}/share ${{env.TTK_MODULE}}/doc
          cp CREDITS.md LICENSE README.md utils/resource/LICENSE.QT-LICENSE-AGREEMENT ${{env.TTK_MODULE}}/doc
          cp utils/install.sh utils/uninstall.sh ${{env.TTK_MODULE}}
          cp -r utils/deploy ${{env.TTK_MODULE}}
          cp -r utils/deploy/share/metainfo ${{env.TTK_MODULE}}/share
          cd ${{env.TTK_MODULE}}
          export LD_LIBRARY_PATH=${{github.workspace}}/contrib/lib:$LD_LIBRARY_PATH
          # add dependency libraries and so on
          linuxdeploy-x86_64.AppImage --executable=${{env.TTK_MODULE}} --appdir=image --plugin=qt
          mv image/usr/lib image/usr/plugins image/usr/bin/qt.conf .
          rm -rf image
          cd ..
          # add portable binary package
          7z a ${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-${{matrix.os}}-${{matrix.qt}}-x64.7z ${{env.TTK_MODULE}}
        working-directory: ${{github.workspace}}

      - name: Build deb package
        run: |
          mv ${{env.TTK_MODULE}}/deploy/make_deb.sh .
          sh make_deb.sh ${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-${{matrix.os}}-${{matrix.qt}}-x64
        working-directory: ${{github.workspace}}

      - name: Archive artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TTK_VERSION}}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: false
          files: |
            ${{github.workspace}}/${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-${{matrix.os}}-${{matrix.qt}}-x64.7z
            ${{github.workspace}}/${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-${{matrix.os}}-${{matrix.qt}}-x64.deb
