# Author: Greedysky <greedysky@163.com>

name: win10

on: workflow_call

env:
  TTK_MODULE: QtSpek
  TTK_VERSTION: 0.8.5

jobs:
  build:
    name: Build on Qt6
    strategy:
      matrix:
        os: [windows-2022]

    env:
      QT_VERSION: 6.5.3
      WIN_MINGW_PATH: c:/mingw64/bin
      UNIX_MINGW_PATH: /c/mingw64/bin

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5

      - name: Cache Qt
        uses: actions/cache@v4
        with:
          path: ${{runner.workspace}}/Qt
          key: ${{runner.os}}-QtCache-${{env.QT_VERSION}}

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{env.QT_VERSION}}
          host: windows
          arch: win64_mingw
          target: desktop
          modules: qt5compat
          cache: 'true'

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            p7zip
            libtool
            make
            texinfo
            autoconf
            automake
            pkg-config

      - name: Build library for libffmpeg
        shell: msys2 {0}
        run: |
          curl -L https://ffmpeg.org/releases/ffmpeg-3.4.14.tar.xz -o ffmpeg.tar.xz
          tar -xvf ffmpeg.tar.xz
          cd ffmpeg-3.4.14
          # fix operand type mismatch for `shr'
          curl -L https://raw.githubusercontent.com/FFmpeg/FFmpeg/refs/heads/master/libavcodec/x86/mathops.h -o libavcodec/x86/mathops.h
          export PATH=${{env.UNIX_MINGW_PATH}}:$PATH
          ./configure --prefix=/d/a/${{env.TTK_MODULE}}/${{env.TTK_MODULE}}/contrib --enable-shared --disable-static --disable-debug --disable-doc --disable-avdevice --disable-x86asm --disable-network --disable-encoders --disable-indevs --disable-outdevs --disable-iconv --disable-bsfs --disable-programs --disable-d3d11va --disable-dxva2 --disable-muxers --disable-parsers --disable-filters --disable-decoders --enable-decoder=wmav1 --enable-decoder=wmav2 --enable-decoder=ape --enable-decoder=tta --enable-decoder=aac --enable-decoder=alac --enable-decoder=ra_144 --enable-decoder=ra_288 --enable-decoder=shorten --enable-decoder=eac3 --enable-decoder=dca --enable-decoder=truehd --enable-decoder=twinvq --enable-decoder=tak --enable-decoder=adpcm_adx --enable-decoder=pcm_alaw --enable-decoder=pcm_s16be --enable-decoder=pcm_s16le --enable-decoder=gsm --enable-decoder=amrnb --enable-decoder=amrwb --enable-decoder=opus --enable-decoder=ac3 --enable-decoder=mp2 --enable-decoder=mp3 --enable-decoder=dsd_lsbf --enable-decoder=dsd_msbf --enable-decoder=vorbis --enable-decoder=flac --extra-cflags="-O3 -Wno-incompatible-pointer-types" --extra-cxxflags="-O3 -Wno-incompatible-pointer-types"
          make -j2 && make install
        working-directory: ${{github.workspace}}

      - name: Build project
        run: |
          qmake -v
          qmake "CONFIG+=release" .
          mingw32-make -j2
        working-directory: ${{github.workspace}}

      - name: Build package
        run: |
          mv bin ${{env.TTK_MODULE}}
          # add dependency libraries and so on
          windeployqt ${{env.TTK_MODULE}}/spek.exe
          # remove useless library dependency
          ls -Filter "*.a" -Recurse | Remove-Item -Force
          # add portable binary package
          7z a ${{env.TTK_MODULE}}-${{env.TTK_VERSTION}}-win10-x64.7z ${{env.TTK_MODULE}}
        working-directory: ${{github.workspace}}

      - name: Archive artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TTK_VERSTION}}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: false
          files: ${{github.workspace}}/${{env.TTK_MODULE}}-${{env.TTK_VERSTION}}-win10-x64.7z
