# Author: Greedysky <greedysky@163.com>

name: winXP

on: workflow_call

env:
  TTK_MODULE: QtSpek
  TTK_VERSION: 0.8.5

jobs:
  build:
    name: Build on Qt4
    strategy:
      matrix:
        ffmpeg: [ffmpeg3]
        os: [windows-2022]
        include:
          - ffmpeg: ffmpeg3
            ffmpeg_version: 3.4.14
            avcodec: 57
            avformat: 57
            avutil: 55
            swresample: 2

    env:
      QT_VERSION: 4.8.7
      QT_ROOT_DIR: D:/a/QtSpek/Qt/4.8.7
      WIN_MINGW_PATH: D:/a/QtSpek/mingw/bin
      UNIX_MINGW_PATH: /d/a/QtSpek/mingw/bin
      INSTALL_PATH: /d/a/QtSpek/QtSpek/contrib

    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v5

      - name: Install Qt
        run: |
          curl -L https://github.com/Greedysky/Resource/releases/download/1.0.0.0/Qt4.7z -o Qt.7z
          7z x Qt.7z -oQt
          "[Paths]`nPrefix = ${{env.QT_ROOT_DIR}}" > ${{env.QT_ROOT_DIR}}/bin/qt.conf
          echo "${{env.QT_ROOT_DIR}}/bin;" >> $env:GITHUB_PATH
        working-directory: ${{runner.workspace}}

      - name: Install MinGW492_32
        run: |
          curl -L https://github.com/Greedysky/Resource/releases/download/1.0.0.0/mingw492_32.7z -o mingw.7z
          7z x mingw.7z -omingw
          # remove default installed mingw64
          mv C:\mingw64 C:\mingw64_useless
          # set environment variable
          echo "${{env.WIN_MINGW_PATH}};" >> $env:GITHUB_PATH
        working-directory: ${{runner.workspace}}

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw32
          update: true
          install: >-
            p7zip
            libtool
            make
            texinfo
            autoconf
            automake
            pkg-config

      - name: Build library for libspeex
        shell: msys2 {0}
        run: |
          curl -L https://ftp.osuosl.org/pub/xiph/releases/speex/speex-1.2.1.tar.gz -o speex.tar.gz
          tar -xvf speex.tar.gz
          cd speex-1.2.1
          export PATH=${{env.UNIX_MINGW_PATH}}:$PATH
          ./configure --prefix=${{env.INSTALL_PATH}} CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libffmpeg
        shell: msys2 {0}
        run: |
          curl -L https://ffmpeg.org/releases/ffmpeg-${{matrix.ffmpeg_version}}.tar.gz -o ffmpeg.tar.gz
          tar -xvf ffmpeg.tar.gz
          cd ffmpeg-${{matrix.ffmpeg_version}}
          # fix operand type mismatch for `shr'
          wget https://raw.githubusercontent.com/FFmpeg/FFmpeg/refs/heads/master/libavcodec/x86/mathops.h -O libavcodec/x86/mathops.h
          export PATH=${{env.UNIX_MINGW_PATH}}:$PATH
          export PKG_CONFIG_PATH=${{env.INSTALL_PATH}}/lib/pkgconfig:$PKG_CONFIG_PATH
          ./configure --prefix=${{env.INSTALL_PATH}} --enable-shared --disable-static --disable-debug --disable-doc --disable-avdevice --disable-x86asm --disable-network --disable-encoders --disable-indevs --disable-outdevs --disable-iconv --disable-bsfs --disable-programs --disable-d3d11va --disable-dxva2 --disable-muxers --disable-parsers --disable-filters --disable-decoders --enable-decoder=wmav1 --enable-decoder=wmav2 --enable-decoder=ape --enable-decoder=tta --enable-decoder=aac --enable-decoder=alac --enable-decoder=ra_144 --enable-decoder=ra_288 --enable-decoder=shorten --enable-decoder=eac3 --enable-decoder=dca --enable-decoder=truehd --enable-decoder=twinvq --enable-decoder=tak --enable-decoder=adpcm_adx --enable-decoder=pcm_alaw --enable-decoder=pcm_s16be --enable-decoder=pcm_s16le --enable-decoder=gsm --enable-decoder=amrnb --enable-decoder=amrwb --enable-decoder=opus --enable-decoder=ac3 --enable-decoder=mp2 --enable-decoder=mp3 --enable-decoder=dsd_lsbf --enable-decoder=dsd_msbf --enable-decoder=vorbis --enable-decoder=flac --enable-decoder=libspeex --enable-libspeex --extra-cflags="-O3" --extra-cxxflags="-O3"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build project
        run: |
          qmake -v
          qmake "CONFIG+=release" .
          mingw32-make -j2
        working-directory: ${{github.workspace}}

      - name: Build package
        run: |
          mv bin ${{env.TTK_MODULE}}
          # add install resource
          mkdir ${{env.TTK_MODULE}}/doc
          cp CREDITS.Spek.md ${{env.TTK_MODULE}}/doc
          cp CREDITS.QtSpek.md ${{env.TTK_MODULE}}/doc
          cp LICENSE ${{env.TTK_MODULE}}/doc
          cp README.md ${{env.TTK_MODULE}}/doc
          cp utils/resource/LICENSE.QT-LICENSE-AGREEMENT ${{env.TTK_MODULE}}/doc
          cp utils/resource/qicon.dll ${{env.TTK_MODULE}}
          cp utils/resource/README.txt ${{env.TTK_MODULE}}
          # copy ffmpeg libraries
          cp contrib/bin/avcodec-${{matrix.avcodec}}.dll ${{env.TTK_MODULE}}
          cp contrib/bin/avformat-${{matrix.avformat}}.dll ${{env.TTK_MODULE}}
          cp contrib/bin/avutil-${{matrix.avutil}}.dll ${{env.TTK_MODULE}}
          cp contrib/bin/swresample-${{matrix.swresample}}.dll ${{env.TTK_MODULE}}
          # add dependency libraries and so on
          cp ${{env.QT_ROOT_DIR}}/plugins/imageformats ${{env.TTK_MODULE}} -Recurse -Container -Force
          cp ${{env.QT_ROOT_DIR}}/bin/QtCore4.dll ${{env.TTK_MODULE}}
          cp ${{env.QT_ROOT_DIR}}/bin/QtGui4.dll ${{env.TTK_MODULE}}
          cp ${{env.WIN_MINGW_PATH}}/libgcc_s_dw2-1.dll ${{env.TTK_MODULE}}
          cp ${{env.WIN_MINGW_PATH}}/libstdc++-6.dll ${{env.TTK_MODULE}}
          cp ${{env.WIN_MINGW_PATH}}/libwinpthread-1.dll ${{env.TTK_MODULE}}
          # remove useless library dependency
          ls -Filter "*.a" -Recurse | Remove-Item -Force
          # add portable binary package
          7z a ${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-winXP-x86.7z ${{env.TTK_MODULE}}
        working-directory: ${{github.workspace}}

      - name: Archive artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{env.TTK_VERSION}}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: false
          files: ${{github.workspace}}/${{env.TTK_MODULE}}-${{env.TTK_VERSION}}-winXP-x86.7z
